# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e14509c8699cb8e34dcbf2cc8cbed075376950b7c20c3281e5a96f9c54d927c2940de8a903c4d536f42d1316546bee48b0dca2c0c7842f4c15f59fedc81b08fe

test:
  secret_key_base: d97e9ca54191118eb15b148bdc64fc1c4b961cdfe194833705f1360a483a2a7e1ebf42a0cfb07e102cdf6264962e39782f83da1eb3f439fae13830a08b719c8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
